---

sudo: required

# Only test Ubuntu 14.04 for scrum-1
env:
  - distro: ubuntu1404
    init: /sbin/init
    run_opts: ""


before_install:
  # Pull container from Docker Hub.
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'
  # ansible.cfg creation moved to docker file.

script:
 # Create a random file to store the container ID.
 - container_id=$(mktemp)

 # Run container detached, with our role mounted inside.
 - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/web-automation:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

 - 'docker exec --tty ${container_id} env TERM=xterm which java'
 
 - 'docker exec --tty ${container_id} env TERM=xterm java -version'
 
 - docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/web-automation/tests/test.yml --syntax-check

 - docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/web-automation/tests/test.yml

 - idempotence=$(mktemp)
 
 - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
   
 - tail ${idempotence} | grep -q "changed=0.*failed=0" && (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && exit 1)

notifications:
 webhooks: https://galaxy.ansible.com/api/v1/notifications/